steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/kakarot1994/istio-test"]
    env: ["PROJECT_ROOT=github.com/kakarot1994/istio-test"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/ws-microservices-production/istio-test:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/ws-microservices-production/istio-test:$REVISION_ID"
